spring.application.name=inventarios
#Conexion a mysql
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Configuramos el patron del log
logging.pattern.console=[%thread] %-5level - %msg%n
# configurar el nivel del log
logging.level.root=INFO
# Cambiar el puerto de tomcat
#server.port=8080
spring.main.banner-mode=off

